[template]
ignore = ["uv.lock"]

[placeholders]
vscode_settings = { prompt = "Generate default VS Code settings?", default = false, type = "bool" }

[conditional.'vscode_settings == false']
ignore = [".vscode"]
